### ISSUE TITLE
Linear transformation for latitude and longitude might not be good enough

### ISSUE THREAD

**Issue by MakeNEnjoy** [MakeNEnjoy/interactive-track-and-trace#12]
See the following figure
![image](https://github.com/MakeNEnjoy/interactive-track-and-trace/assets/38182125/29e85767-f26f-4163-bbd6-c3d6d20bd279)
Especially in latitude, the intended coordinates and displayed coordinates are quite far apart for the middle sections of the image. Possibly a more complex transformation could resolve this. Hopefully such an improved transformation is still homogeneous 🤞.

**Comment by djairoh** [comment]
I've done a little experimenting with the transformation matrix as well, but I can't actually determine where the problem lies. I doubt it's fpe; the difference for the point in Groningen specifically is quite large. Manually adding a particle on top of Groningen outputting the wrong coordinates also supports this. 

Have you done any testing/debugging for this one @MakeNEnjoy ?

**Comment by MakeNEnjoy** [comment]
My observation is that the points do look correct on the top and bottom, but do not look correct in the middle of the image. I'm sure there exists a transformation that can correct for this.

**Comment by djairoh** [comment]
i generated some more glyphs using the following loops
![image](https://github.com/MakeNEnjoy/interactive-track-and-trace/assets/99992600/14b97e8a-487e-46a9-ae9e-ab08a8e02e2a)

which produces these glyphs
![image](https://github.com/MakeNEnjoy/interactive-track-and-trace/assets/99992600/41bc5710-3000-4d0d-8d32-645439cae624)

I also decreased the glyphsize and then panned the camera around the zoomed in particles, and they all line up to the same display coordinates. If it was fpe i'd expect at least some of the glyphs to be out of line with the others.

**Comment by djairoh** [comment]
I also checked the actual image we're using for the background - this lines up with the latitude/longitudes used as well, so that shouldn't be the problem either.

**Comment by MakeNEnjoy** [comment]
Your glyph grid looking regular makes 100% sense to me. I'm saying the grid looks regular because we're doing linear interpolation between coordinates and screen space. The point is that the map image (i.e screen space) in contrast is not linear, it's got some more complex projection, probably a mercator projection. Therefore I'm suggesting we change the projection in `CartographicTransformation.cpp` so that if you make a grid spaced equally in lat/lons, the particles DO look more bunched up in the centre and more spread out on the sides. (Which they currently don't)

**Comment by MakeNEnjoy** [comment]
I will send Christian an email about this
