### ISSUE TITLE
eps value when beaching

### ISSUE THREAD

**Issue by djairoh** [MakeNEnjoy/interactive-track-and-trace#33]
I'm working a bit more on our particle beaching logic, but theres a (pretty predictable) issue: because of the non-uniform nature of the coastlines, values of epsilon large enough to do anything appreciable on the Scandinavian cost will lead to a decent number of false positives closer to the English channel. 

![image](https://github.com/MakeNEnjoy/interactive-track-and-trace/assets/99992600/1712ec96-3353-4421-916f-fa4fbffacca6)
![image](https://github.com/MakeNEnjoy/interactive-track-and-trace/assets/99992600/00fae4bf-7439-43f4-af08-7db095def9cb)

Doing some manual testing I can't find a sweet spot value for epsilon with an acceptable number of false positives. As a result, I think it would be best to just accept some unnecessary computations for particles which are beached but still advecting slightly.

**Comment by djairoh** [comment]
@MakeNEnjoy any thoughts?

**Comment by MakeNEnjoy** [comment]
I think I solved this with a new function named `isNearestNeighbourZero` that checks whether at least 4 nearestneighbor velocities are equal to 0.
