### ISSUE TITLE
The Us and Vs might be flipped around - investigate

### ISSUE THREAD

**Issue by MakeNEnjoy** [MakeNEnjoy/interactive-track-and-trace#9]
There are some inconsistencies.
## In the `.h5` files
In `hydrodynamic_V.h5` the header information says "zonal_velocity".
In `hydrodynamic_U.h5` the header information says "meridional_velocity".

## Wikipedia
For what it's worth, [wikipedia](https://en.wikipedia.org/wiki/Zonal_and_meridional_flow) says

> For [vector fields](https://en.wikipedia.org/wiki/Vector_field) (such as [wind velocity](https://en.wikipedia.org/wiki/Wind_velocity)), the zonal component (or x-[coordinate](https://en.wikipedia.org/wiki/Coordinate)) is denoted as u, while the meridional component (or y-coordinate) is denoted as v.

## NetCDF files
The `.nc` files in the header information say that
`vo` is "Northward Current Velocity in the Water Column" and `uo` is  "Eastward Current Velocity in the Water Column".

## Parcels
In [advection.py](https://github.com/OceanParcels/parcels/blob/daa4b062ed8ae0b2be3d87367d6b45599d6f95db/parcels/application_kernels/advection.py#L10) in Parcels, `u`s affect longitude and `v`s affect latitude.

## Experimentally
For what it's worth, I'm currently using `u`s to affect latitude and `v`s to affect longitude and the outputs _look_ good.

## Conclusion - What is the problem?
The original data uses `u` to mean Eastward Velocity (== affects latitude == `x` == zonal velocity) however parcels uses `u` to mean affects longitude (== Northward Velocity == `y` == meridional velocity).

I suspect that Christian mixed this up as a result when converting the NetCDF files because to me it seems that the `u`s in the hdf5 data are actually indicating zonal velocity and this means that the hdf5 headers are named incorrectly.

**Comment by CKehl** [comment]
Comment 1:
Latitude = North-South ( https://en.wikipedia.org/wiki/Latitude ) = y
Longitude = East-West ( https://en.wikipedia.org/wiki/Longitude ) = x

Comment 2:
"Zonal flow follows a pattern along [latitudinal](https://en.wikipedia.org/wiki/Latitude) lines, [latitudinal circles](https://en.wikipedia.org/wiki/Circle_of_latitude) or in the west–east direction." -> Zonal flow occurs along a *fixed* latitude (i.e. a line at a given latitude), 'along' meaning here: "on that line". So, this should be *U*. (I need to correct the H5-description).

"Meridional flow follows a pattern from north to south, or from south to north, along the Earth's [longitude](https://en.wikipedia.org/wiki/Longitude) lines, [longitudinal circles](https://en.wikipedia.org/wiki/Circle_of_longitude) ([meridian](https://en.wikipedia.org/wiki/Meridian_(geography))) or in the north–south direction." -> Meridional flow occurs along a meridian (i.e. a fixed longitude - a line along a meridian, with a meridian always having the same x-coordinate; see the Greenich zero-meridian). So, this should be *V*. (I need to correct the H5-description).


Suggestion:
Now, to check what is what, I suggest the following:
a) post here please the coordinates of your test-cases. I'll quickly run them today or tomorrow through parcels, and give you the reference trajectory.
b) Maybe please look again on the major-order of your loaded array and your looped indexing. Maybe you switched x- and y indices  during your loop, or reading in a column-major order field [time][y][x] as row-major order field [x][y][time] ? This could easily happen sometimes with the memory map.

**Comment by MakeNEnjoy** [comment]
> Comment 1:
> Latitude = North-South ( https://en.wikipedia.org/wiki/Latitude ) = y
> Longitude = East-West ( https://en.wikipedia.org/wiki/Longitude ) = x

Ah!! This explains part of my confusion. I was looking at this image and the arrows totally confused me.
![image](https://github.com/MakeNEnjoy/interactive-track-and-trace/assets/38182125/146730fb-61c3-49e2-bd52-c515f77fb634)

A reference trajectory would be greatly appreciated. I tried some more value looking for a good trajectory and I found one that gives me quite strange results so there is definitely still something not right with my implementation.

Please can you send me trajectory for start latitude = 54.832040 and start longitude = 6.187572?

**Comment by MakeNEnjoy** [comment]
> b) Maybe please look again on the major-order of your loaded array and your looped indexing. Maybe you switched x- and y indices during your loop, or reading in a column-major order field [time][y][x] as row-major order field [x][y][time] ? This could easily happen sometimes with the memory map

I think I indeed found an error here that seems to have cleared up at least one problem. So thank you for this!
